
[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/assets/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "assets/images/*.svg"
    [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "assets/images/*"
    [headers.values]
    Cache-Control = "public, max-age=604800"
